version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://root:password@db:27017/mydatabase?authSource=admin
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

volumes:
  mongodb_data_container:

networks:
  app-network:
    driver: bridge